# Data Processing

In [258]:
import tensorflow

In [259]:
import pandas as pd
cancer = pd.read_csv("breastcancer.csv")

In [260]:
cancer=cancer.drop(columns='Unnamed: 32')
cancer['diagnosis']=cancer['diagnosis'].replace({
    "M":1, "B":0
})
cancer.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [261]:
features=cancer.iloc[:,2:-1].dropna(axis=1)
features.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364

In [262]:
X=features.to_numpy()
X=X.astype(float)
print(X.shape)

(569, 29)

In [263]:
target=cancer['diagnosis']
y=target.to_numpy()
y=y.astype(float)
print(y.shape)

(569,)

In [264]:
import torch
from torch.utils.data import TensorDataset

In [265]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_val,
    y_val,
    test_size=0.40,
    random_state=42,
    stratify=y_val
)

In [266]:
datasetTrain = TensorDataset(torch.tensor(X_train),torch.tensor(y_train))
datasetVal = TensorDataset(torch.tensor(X_val),torch.tensor(y_val))
datasetTest = TensorDataset(torch.tensor(X_test),torch.tensor(y_test))
x1,y1 = datasetTrain[0]
print("Features:",x1) 
print("Target:",y1)

Features: tensor([1.6020e+01, 2.3240e+01, 1.0270e+02, 7.9780e+02, 8.2060e-02, 6.6690e-02,
        3.2990e-02, 3.3230e-02, 1.5280e-01, 5.6970e-02, 3.7950e-01, 1.1870e+00,
        2.4660e+00, 4.0510e+01, 4.0290e-03, 9.2690e-03, 1.1010e-02, 7.5910e-03,
        1.4600e-02, 3.0420e-03, 1.9190e+01, 3.3880e+01, 1.2380e+02, 1.1500e+03,
        1.1810e-01, 1.5510e-01, 1.4590e-01, 9.9750e-02, 2.9480e-01],
       dtype=torch.float64)
Target: tensor(1., dtype=torch.float64)

In [267]:
from torch.utils.data import DataLoader

batch_size = 5 #receive 5 samples at a time
shuffle = True

trainLoader = DataLoader(datasetTrain, batch_size=batch_size,shuffle=shuffle)
valLoader = DataLoader(datasetVal, batch_size=batch_size,shuffle=shuffle)
testLoader = DataLoader(datasetTest, batch_size=batch_size,shuffle=shuffle)

In [268]:
import torch.nn as nn

print(X.shape) #(569, 29)
model = nn.Sequential(
    nn.Linear(29,10),
    nn.ReLU(),
    nn.Linear(10,5),
    nn.ReLU(),
    nn.Linear(5,1),
    nn.Sigmoid()
)
x1=x1.float()
print(model(x1))

(569, 29)
tensor([8.3977e-09], grad_fn=<SigmoidBackward0>)

In [269]:
import torch.optim as optim

In [270]:
criterion = nn.BCELoss() #loss function to be used
optimizer = optim.SGD(model.parameters(),lr=0.001)

In [271]:

for epoch in range(13):
    for data in trainLoader: #training loop for training data
        optimizer.zero_grad() #set original gradient to 0 
        feature,target = data
        feature=feature.float()
        target=target.float()
        pred=model(feature).squeeze(1)
        loss = criterion(pred,target)
        train_loss = loss.item()
        loss.backward() #gradients are calculated
        optimizer.step() #weights are updated
    mean_train_loss = train_loss/len(trainLoader)
    model.eval() #switching to models evaluation mode
    validation_loss=0
    with torch.no_grad(): #disable gradients
        for inputs, labels in valLoader:
            inputs=inputs.float()
            labels=labels.float()
            outputs = model(inputs).squeeze(1)
            loss = criterion(outputs,labels)
            validation_loss = loss.item()

        mean_loss = validation_loss/len(valLoader)
    print("Train Loss:",mean_train_loss,"Validation Loss:",mean_loss)
    model.train()

Train Loss: 0.007201873994135594 Validation Loss: 0.04771304130554199
Train Loss: 0.008054840040730905 Validation Loss: 0.047700153929846625
Train Loss: 0.00795741985132406 Validation Loss: 0.04745032957621983
Train Loss: 0.007350803076565921 Validation Loss: 0.04609777246202741
Train Loss: 0.007579443218943837 Validation Loss: 0.04825038995061602
Train Loss: 0.009207386891920489 Validation Loss: 0.046419624771390645
Train Loss: 0.006215937190003447 Validation Loss: 0.04019708718572344
Train Loss: 0.007106257663978325 Validation Loss: 0.030192641275269643
Train Loss: 0.00454133323260716 Validation Loss: 0.0348846401487078
Train Loss: 0.004180382241259564 Validation Loss: 0.03833062733922686
Train Loss: 0.0053369648508973175 Validation Loss: 0.05212480681283133
Train Loss: 0.005101210795916044 Validation Loss: 0.028911533100264415
Train Loss: 0.0027616705213274273 Validation Loss: 0.021174603274890354

In [272]:
import torchmetrics

metric = torchmetrics.Accuracy(task="binary")
with torch.no_grad():
    for features, labels in testLoader:
        features=features.float()
        labels=labels.float()
        outputs = model(features).squeeze(1)
        metric.update(outputs,labels)

accuracy= metric.compute()
print(accuracy)
metric.reset()

tensor(0.9130)